# Playwrightの公式Dockerイメージを使用
FROM mcr.microsoft.com/playwright:v1.44.1-jammy

RUN ln -sf /usr/share/zoneinfo/Asia/Tokyo /etc/localtime

# 必要な追加の依存関係をインストール
RUN apt update && \
    apt -y upgrade && \
    apt install -y sudo tzdata build-essential git wget time curl libssl-dev zlib1g-dev libnss3 libatk-bridge2.0-0 libdrm2 libxkbcommon0 libgbm1

# cirq のインストール
RUN apt install -y software-properties-common
RUN add-apt-repository ppa:deadsnakes/ppa
RUN apt -y update
RUN apt install -y python3.8 pip

# set python 3 as the default python version
RUN update-alternatives --install /usr/bin/python python /usr/bin/python3 1 \
    && update-alternatives --install /usr/bin/pip pip /usr/bin/pip3 1
RUN pip3 install --upgrade pip requests setuptools pipenv

RUN python -m pip install --upgrade pip
RUN python -m pip install cirq

# Node.jsのインストール
RUN curl -fsSL https://deb.nodesource.com/setup_lts.x | sudo -E bash - && \
    apt install -y nodejs

# npmのインストール
RUN curl -qL https://www.npmjs.com/install.sh | sh

# yarnのインストール
RUN npm install -g yarn

# nginx 等のインストール
RUN apt install -y nginx apache2-utils uwsgi python3-flask uwsgi-plugin-python3 && \
    rm -rf /var/lib/apt/lists/* /var/cache/apt/archives

# 設定ファイル
COPY backend_flask/merged.conf /etc/nginx/conf.d/
# COPY .htpasswd /etc/nginx/
RUN htpasswd -bc /etc/nginx/.htpasswd userA passA

# エントリーポイントスクリプトをコピーし、実行権限を付与
COPY docker-entrypoint.sh /usr/local/bin/
RUN chmod +x /usr/local/bin/docker-entrypoint.sh

# 開発サーバーを開始するためのコマンド
ENTRYPOINT ["docker-entrypoint.sh"]

# デフォルトコマンドを設定
CMD ["/bin/bash"]
