# イメージのビルド
#   docker build -f Dockerfile.flask-test . -t qni-gl-flask
# イメージの実行
#   docker run -p 8000:8000 --rm -it -v .:/qni-gl qni-gl-flask

# Playwright の公式 Docker イメージを使用
FROM mcr.microsoft.com/playwright:v1.44.1-jammy

RUN ln -sf /usr/share/zoneinfo/Asia/Tokyo /etc/localtime

# 必要な追加の依存関係をインストール
RUN apt update && \
  apt -y upgrade && \
  apt install -y tzdata build-essential git curl libssl-dev zlib1g-dev libnss3 libatk-bridge2.0-0 libdrm2 libxkbcommon0 libgbm1

# cirq のインストール
RUN apt install -y software-properties-common
RUN add-apt-repository ppa:deadsnakes/ppa
RUN apt -y update
RUN apt install -y python3.8 pip

# set python 3 as the default python version
RUN update-alternatives --install /usr/bin/python python /usr/bin/python3 1 \
  && update-alternatives --install /usr/bin/pip pip /usr/bin/pip3 1
RUN pip3 install --upgrade pip requests setuptools pipenv

RUN python -m pip install --upgrade pip
RUN python -m pip install cirq

# Node.jsのインストール
RUN curl -fsSL https://deb.nodesource.com/setup_lts.x | bash - && \
  apt install -y nodejs

# npmのインストール
RUN curl -qL https://www.npmjs.com/install.sh | sh

# yarnのインストール
RUN npm install -g yarn

# nginx 等のインストール
RUN apt install -y nginx apache2-utils uwsgi python3-flask uwsgi-plugin-python3 && \
  rm -rf /var/lib/apt/lists/* /var/cache/apt/archives

# nginx 用の設定ファイルを準備
COPY backend_flask/merged.conf /etc/nginx/conf.d/
RUN htpasswd -bc /etc/nginx/.htpasswd userA passA

# 非特権ユーザーの作成と権限設定
RUN useradd -m -d /home/uwsgi -s /bin/bash uwsgiuser && \
  chown -R uwsgiuser:uwsgiuser /tmp /var/log/uwsgi /etc/nginx

# vite のビルドと nginx の起動
COPY docker-entrypoint.sh /usr/local/bin/
RUN chmod +x /usr/local/bin/docker-entrypoint.sh
ENTRYPOINT ["docker-entrypoint.sh"]

# uWSGI を起動
CMD ["uwsgi", "--chdir", "/qni-gl/backend_flask", "--ini", "/qni-gl/backend_flask/backend.ini", "--uid", "uwsgiuser", "--gid", "uwsgiuser", "--master"]
