version: '3.8'
services:
  rails:
    image: backend_rails
    build:
      context: ./backend_rails
    ports:
      - "3000:3000"
    volumes:
      - ./rails:/app
    environment:
      - RAILS_ENV=development
    networks:
      - mynetwork

  vite:
    image: vite
    build:
      context: ./vite
    ports:
      - "5173:5173"
    volumes:
      - ./vite:/app
    depends_on:
      - rails
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
