[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "qni"
dynamic = ["version"]
description = ""
readme = "README.md"
requires-python = ">=3.8"
license = "MIT"
keywords = []
authors = [
  { name = "Yasuhito Takamiya", email = "yasuhito@hey.com" },
]
classifiers = [
  "Development Status :: 4 - Beta",
  "Programming Language :: Python",
  "Programming Language :: Python :: 3.8",
  "Programming Language :: Python :: 3.9",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.12",
  "Programming Language :: Python :: Implementation :: CPython",
  "Programming Language :: Python :: Implementation :: PyPy",
]
dependencies = [
  "cirq",
  "flask-cors",
  "gunicorn",
"pytest"
]

[project.urls]
Documentation = "https://github.com/yasuhito/qni#readme"
Issues = "https://github.com/yasuhito/qni/issues"
Source = "https://github.com/yasuhito/qni"

[tool.hatch.version]
path = "qni/__init__.py"

[tool.hatch.envs.types]
extra-dependencies = [
  "mypy>=1.0.0",
]
[tool.hatch.envs.types.scripts]
check = "mypy --install-types --non-interactive {args:src/qni tests}"

[tool.coverage.run]
source_pkgs = ["src", "tests"]
branch = true
parallel = true
omit = [
  "src/qni/__about__.py",
]

[tool.coverage.paths]
qni = ["src"]
tests = ["tests"]

[tool.coverage.report]
exclude_lines = [
  "no cov",
  "if __name__ == .__main__.:",
  "if TYPE_CHECKING:",
]
