name: Playwright Tests
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 18
    - name: Set up Python
      # This is the version of the action for setting up Python, not the Python version.
      uses: actions/setup-python@v4
      with:
        # Semantic version range syntax or exact version of a Python version
        python-version: '3.x'
    # You can test your matrix by printing the current Python version
    - name: Display Python version
      run: python -c "import sys; print(sys.version)"
    - name: Setup backend_rails/
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7.4
        working-directory: backend_rails/
        bundler-cache: true
    - name: Install dependencies (pip)
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
      working-directory: vite/
    - name: Install dependencies (yarn)
      run: yarn
      working-directory: vite/
    - name: Install Playwright Browsers
      run: yarn playwright install --with-deps
      working-directory: vite/
    - name: Run backend server
      run: yarn backend -d
      working-directory: vite/
    - name: Run Playwright tests
      run: yarn playwright test
      working-directory: vite/
    - uses: actions/upload-artifact@v3
      if: always()
      with:
        name: playwright-report
        path: vite/playwright-report/
        retention-days: 30
