name: Playwright Tests
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12"]

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: Install dependencies (yarn)
        run: yarn
        working-directory: ./frontend
      - name: Install Playwright Browsers
        run: yarn playwright install --with-deps
        working-directory: ./frontend
      - name: Setup Python ${{ matrix.python-version }} with uv
        uses: ./.github/actions/setup-python-with-uv
        with:
          python-version: ${{ matrix.python-version }}
      - name: Run backend server
        run: |
          uv run gunicorn --daemon
        working-directory: ./backend
      - name: Run frontend tests
        run: yarn test:unit
        working-directory: ./frontend
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: frontend/playwright-report/
          retention-days: 30
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: access-log
          path: backend/access.log
          retention-days: 30
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: error-log
          path: backend/error.log
          retention-days: 30
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: backend-log
          path: backend/backend.log
          retention-days: 30
