name: Playwright Tests
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: Install Hatch
        uses: pypa/hatch@install
      - name: Check code formatting
        run: hatch fmt
        working-directory: ./backend
      - name: Check Python types
        run: hatch run types:check
        working-directory: ./backend
      - name: Run backend tests
        run: hatch test -c
        working-directory: ./backend
      - name: Install dependencies (yarn)
        run: yarn
        working-directory: ./frontend
      - name: Install Playwright Browsers
        run: yarn playwright install --with-deps
        working-directory: ./frontend
      - name: Run backend server
        run: |
          hatch run gunicorn --daemon
        working-directory: ./backend
      - name: Run frontend unit tests
        run: yarn test:unit
        working-directory: ./frontend
      - name: Run frontend system tests
        run: yarn test:system
        working-directory: ./frontend
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: frontend/playwright-report/
          retention-days: 30
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: access-log
          path: backend/access.log
          retention-days: 30
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: error-log
          path: backend/error.log
          retention-days: 30
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: backend-log
          path: backend/backend.log
          retention-days: 30
