name: Visual Regression Test

on:
  pull_request:
    branches:
      - master

jobs:
  visual-regression-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          start: yarn dev
          wait-on: "http://localhost:5173/"
          command-prefix: "percy exec -- cypress run"
        env:
          PERCY_TOKEN: ${{ secrets.PERCY_TOKEN }}
